"""Constants for the Jet2 integration."""

DOMAIN = "jet2"
HOST = "https://mobile-api.jet2.com/holidays/booking"
CONF_BOOKING_REFERENCE = "booking_reference"
CONF_BOOKINGREFERENCE = "bookingReference"
CONF_DATE_OF_BIRTH = "date_of_birth"
CONF_DATEOFBIRTH = "dateOfbirth"
CONF_SURNAME = "surname"
CONF_ADD_BOOKING = "add_booking"
CONF_REMOVE_BOOKING = "remove_booking"
CONF_BOOKING_REMOVED = "booking_removed"
CONF_CALENDARS = "calendars"
CONF_CREATE_CALENDAR = "create_calendar"
ADD_BOOKING = "Add Booking"
REMOVE_BOOKING = "Remove Booking"
BOOKING_OPTION = "booking_option"
