add_booking:
  target:
    entity:
      domain: calendar
      supported_features:
        - calendar.CalendarEntityFeature.CREATE_EVENT
  fields:
    create_calendar:
      description: "Create a new calendar"
      required: true
      selector:
        boolean:
    booking_reference:
      required: true
      selector:
        text:
    date_of_birth:
      required: true
      selector:
        text:
    surname:
      required: true
      selector:
        text:
remove_booking:
  fields:
    bookingReference:
      required: true
      selector:
        text: